<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-488FP15" name="Com.ActiTime.Tests.InvalidLoginTest" tests="3" failures="1" timestamp="26 Jun 2019 06:21:19 GMT" time="147.829" errors="0">
  <testcase name="InvalidLogin" time="31.609" classname="Com.ActiTime.Tests.InvalidLoginTest"/>
  <testcase name="InvalidLogin" time="29.503" classname="Com.ActiTime.Tests.InvalidLoginTest"/>
  <testcase name="InvalidLogin" time="86.717" classname="Com.ActiTime.Tests.InvalidLoginTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at Com.ActiTime.Generic.BasePage.verifyElement(BasePage.java:42)
at Com.ActiTime.Pages.actiTIMELoginPage.verifyErrorMsg(actiTIMELoginPage.java:39)
at Com.ActiTime.Tests.InvalidLoginTest.InvalidLogin(InvalidLoginTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- InvalidLogin -->
</testsuite> <!-- Com.ActiTime.Tests.InvalidLoginTest -->
